### ISSUE TITLE
Release a new version to npm

### ISSUE THREAD

**Issue by floqqi** [tim-evans/ember-plupload#111]
Is it possible to release a new version to npm? There's a (merged) fix I need and I don't want to use the git repository as a dependency.

**Comment by tim-evans** [comment]
I don't see any changes to this repository other than upgrades. What version are you running?

**Comment by tim-evans** [comment]
Oh, looks like the release didn't go through. Lemme fix.

**Comment by tim-evans** [comment]
Correction: the release is out. (See https://www.npmjs.com/package/ember-plupload). The tag wasn't created in git. I just pushed the tag.
