### ISSUE TITLE
Transfer to knownasilya

### ISSUE THREAD

**Issue by tim-evans** [tim-evans/ember-plupload#133]
@knownasilya could I transfer this over to your Github account?

**Comment by tim-evans** [comment]
Super! You'll need to delete your fork for me to be able to transfer ownership.

**Comment by knownasilya** [comment]
Done

**Comment by tim-evans** [comment]
🎉

**Comment by tim-evans** [comment]
I've started the transfer; waiting for you to complete it 👍

**Comment by knownasilya** [comment]
Weird, it sent it to my old email, not my primary one.

**Comment by knownasilya** [comment]
Looks like the request expired, could you try again. This time I'll know to check my old email.

**Comment by tim-evans** [comment]
Ok!
