### ISSUE TITLE
queue.progress is only showing the % progress of 1 image

### ISSUE THREAD

**Issue by Paskalouis** [tim-evans/ember-plupload#41]
>{{#if uploadingInProgress}}<b> | {{queue.progress}}%</b>

If I upload more than 1 file, the queue.progress only shows the progress of 1st image, while for the subsequent images uploaded, the progress is not shown. (but upload still complete)

Is there any way to show the progress of EVERY uploaded image one by one ?

Thanks in advance !

**Comment by tim-evans** [comment]
Hmm... I have tests written for this. 

https://github.com/tim-evans/ember-plupload/blob/master/tests/unit/services/uploader-test.js#L71-L117
https://github.com/tim-evans/ember-plupload/blob/master/tests/unit/system/upload-queue-test.js#L68-L81

Could you write a failing test for this? Cheers!

**Comment by tim-evans** [comment]
Resolved in the newest release- thanks for @schwabix for catching this!
