### ISSUE TITLE
Computer properties in uploader service not updated

### ISSUE THREAD

**Issue by schwabix** [tim-evans/ember-plupload#47]
I injected the uploader service in my controller but its properties didn't get updated. I tracked it down to the findOrCreate function in the /addon/services/uploader.js file

```javascript
get(this, 'all').push(queue);
```

should be

```javascript
get(this, 'all').pushObject(queue);
```

With the change applied everything works like a charm.

**Comment by tim-evans** [comment]
Oooh! Good catch :+1:

**Comment by schwabix** [comment]
That was fast - thank you
