### ISSUE TITLE
Turn off moxie logging?

### ISSUE THREAD

**Issue by dasnixon** [tim-evans/ember-plupload#57]
Is there a way to stop moxie from logging? I was looking through their source but don't see a trivial way to do so. Thanks for taking a look.

**Comment by splattne** [comment]
In `plupload/js/moxie.js` just change 

`;var MXI_DEBUG = true;` 

to

`;var MXI_DEBUG = false;`

**Comment by tim-evans** [comment]
(.______ .)

Oh dear. I wish I could make this easier for y'all.

**Comment by splattne** [comment]
Could you please release a new version for this change if you have time? Thanks!

**Comment by tim-evans** [comment]
Released!
