### ISSUE TITLE
upload-queue.js:198 Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by c0achmcguirk** [tim-evans/ember-plupload#65]
I just started seeing this when using ember-plupload to upload directly to Amazon S3 using a version 4 signature.

I'm getting response headers that look like this:

    HTTP/1.1 204 No Content
    x-amz-id-2: Ab5taScd/efgssAnOhiJKLmg3TA3hE/6opQwniLzyxwI107dGv/U1455ZS/WU8mk
    x-amz-request-id: AXXXXXXXXXXXXXXE
    Date: Wed, 06 Apr 2016 20:48:14 GMT
    Access-Control-Allow-Origin: *
    Access-Control-Allow-Methods: GET, POST
    Access-Control-Max-Age: 36000
    Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
    ETag: "ab94abcde12340a6e15c9c8b6ab2c39f"
    Location: https://somebucket.s3.amazonaws.com/somefile.abc
    Server: AmazonS3

The error happens on the second header:

    x-amz-id-2: Ab5taScd/efgssAnOhiJKLmg3TA3hE/6opQwniLzyxwI107dGv/U1455ZS/WU8mk

And it's because of this line on line 191 of `addon/system/upload-queue.js`

    var parts = header.split(/^([A-Za-z_-]*:)/);

The `2` in the header is making the regex sad. So I changed it to this:

    var parts = header.split(/^([0-9A-Za-z_-]*:)/);

And it now works for me.

**Comment by tim-evans** [comment]
Thanks for this fix! :+1:

**Comment by tim-evans** [comment]
Putting out release `1.13.14` now~
