### ISSUE TITLE
BaseURL has been removed from Ember CLI 2.7

### ISSUE THREAD

**Issue by splattne** [tim-evans/ember-plupload#73]
In `app/components/pl-uploader.js` there is a reference to the app's configuration.baseURL. This property has been deprecated and removed in the now current version (2.7+)

http://emberjs.com/blog/2016/04/28/baseURL.html

This causes an exception:

 ```
  if (BASE_URL == null) {
     if (config.baseURL.slice(-1) === '/') { // <--- HERE!
       BASE_URL = config.baseURL + 'assets/';
     } else {
       BASE_URL = config.baseURL + '/assets/';
     }
   }
```

**Comment by tim-evans** [comment]
Ok! Will fix ASAP 👍
