### ISSUE TITLE
Callback after uploading files.

### ISSUE THREAD

**Issue by Rafalsonn** [tim-evans/ember-plupload#77]
I want the ember to show how many files were uploaded, and I don't know where to start. I think the function i need is the callback,

 I'm using standard samples from ember-plupload and node-pluploader. How to do that?

Greetings, Rafał !

**Comment by Rafalsonn** [comment]
Or is there any function, or way to show how many files were uploaded succesfully, for user to see?

**Comment by tim-evans** [comment]
You could count how many `file.upload()` Promises resolve to figure this out

**Comment by tim-evans** [comment]
The queue automatically gets flushed when all files have finished uploading so the progress is correct when another file is uploaded after

**Comment by tim-evans** [comment]
For global stats, inject the `uploader` service

**Comment by Rafalsonn** [comment]
It works, great idea :-) Thanks very much. I've got only one question also, how to implement an action, after the all files have been uploaded?
